# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79f2a3da86dcb79075312ab06d28d7095a0d7ee01250df07ec99d4e2a698c0c1f40c1e123183a5fb92f32ba8f4c7bda5363b5568f11e28b59d5d1508fb400c18

test:
  secret_key_base: 8400c696280bc74372b9562274a7004c4e06a128704732901a99b098a938f66fa724c790b35637365280cbd772bf8360fc8fa62387cce0edad9ad1e7ed9980a7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
